name: Cyclic Imports
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

jobs:
  cyclic-import:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set environment variable
        run: |
          echo $(poetry run poetry env info --path)/bin >> $GITHUB_PATH

      - name: Install packages
        run: |
          make config-poetry
          make install-all

      - name: Show installed packages
        run: |
          poetry show
          poetry show --tree

      - name: check arctix
        run: |
          python -c "import arctix"
      - name: check arctix.dataset
        run: |
          python -c "from arctix import dataset"
      - name: check arctix.utils
        run: |
          python -c "from arctix import utils"
